export const routePageLoaders = {
  ForgotPasswordPage: () =>
    import("../features/auth/ForgotPasswordPage").then(({ ForgotPasswordPage }) => ({ default: ForgotPasswordPage })),
  GoogleCallbackPage: () =>
    import("../features/auth/GoogleCallbackPage").then(({ GoogleCallbackPage }) => ({ default: GoogleCallbackPage })),
  LoginPage: () =>
    import("../features/auth/LoginPage").then(({ LoginPage }) => ({ default: LoginPage })),
  MfaVerifyPage: () =>
    import("../features/auth/MfaVerifyPage").then(({ MfaVerifyPage }) => ({ default: MfaVerifyPage })),
  ResetPasswordPage: () =>
    import("../features/auth/ResetPasswordPage").then(({ ResetPasswordPage }) => ({ default: ResetPasswordPage })),
  SignupPage: () =>
    import("../features/auth/SignupPage").then(({ SignupPage }) => ({ default: SignupPage })),
  BillingCreatePage: () =>
    import("../features/billings/BillingCreatePage").then(({ BillingCreatePage }) => ({ default: BillingCreatePage })),
  BillingDetailPage: () =>
    import("../features/billings/BillingDetailPage").then(({ BillingDetailPage }) => ({ default: BillingDetailPage })),
  BillingEditPage: () =>
    import("../features/billings/BillingEditPage").then(({ BillingEditPage }) => ({ default: BillingEditPage })),
  BillingListPage: () =>
    import("../features/billings/BillingListPage").then(({ BillingListPage }) => ({ default: BillingListPage })),
  BillDetailPage: () =>
    import("../features/bills/BillDetailPage").then(({ BillDetailPage }) => ({ default: BillDetailPage })),
  BillEditPage: () =>
    import("../features/bills/BillEditPage").then(({ BillEditPage }) => ({ default: BillEditPage })),
  BillGeneratePage: () =>
    import("../features/bills/BillGeneratePage").then(({ BillGeneratePage }) => ({ default: BillGeneratePage })),
  CommunicationComposePage: () =>
    import("../features/bills/CommunicationComposePage").then(({ CommunicationComposePage }) => ({ default: CommunicationComposePage })),
  InviteListPage: () =>
    import("../features/invites/InviteListPage").then(({ InviteListPage }) => ({ default: InviteListPage })),
  PrivacyPolicyPage: () =>
    import("../features/legal/PrivacyPolicyPage").then(({ PrivacyPolicyPage }) => ({ default: PrivacyPolicyPage })),
  TermsPage: () =>
    import("../features/legal/TermsPage").then(({ TermsPage }) => ({ default: TermsPage })),
  NotFoundPage: () =>
    import("../features/notFound/NotFoundPage").then(({ NotFoundPage }) => ({ default: NotFoundPage })),
  OrganizationCreatePage: () =>
    import("../features/organizations/OrganizationCreatePage").then(({ OrganizationCreatePage }) => ({ default: OrganizationCreatePage })),
  OrganizationDetailPage: () =>
    import("../features/organizations/OrganizationDetailPage").then(({ OrganizationDetailPage }) => ({ default: OrganizationDetailPage })),
  OrganizationEditPage: () =>
    import("../features/organizations/OrganizationEditPage").then(({ OrganizationEditPage }) => ({ default: OrganizationEditPage })),
  OrganizationListPage: () =>
    import("../features/organizations/OrganizationListPage").then(({ OrganizationListPage }) => ({ default: OrganizationListPage })),
  RecoveryCodesPage: () =>
    import("../features/security/RecoveryCodesPage").then(({ RecoveryCodesPage }) => ({ default: RecoveryCodesPage })),
  SecurityPage: () =>
    import("../features/security/SecurityPage").then(({ SecurityPage }) => ({ default: SecurityPage })),
  TotpSetupPage: () =>
    import("../features/security/TotpSetupPage").then(({ TotpSetupPage }) => ({ default: TotpSetupPage })),
  SupportPage: () =>
    import("../features/support/SupportPage").then(({ SupportPage }) => ({ default: SupportPage })),
  ThemePage: () =>
    import("../features/themes/ThemePage").then(({ ThemePage }) => ({ default: ThemePage })),
  LandingPage: () =>
    import("../features/landing/LandingPage").then(({ LandingPage }) => ({ default: LandingPage }))
};
